AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Fargate service for adoption"

Parameters:
  DockerImage:
    Type: String
    Description: datamorphproject/datamorph:latest

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [FARGATE]
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: sample-ecs-datamorph
          Image: !Ref DockerImage
          PortMappings:
            - ContainerPort: 8501 # Replace with an unique port value
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/sample-ecs-datamorph
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/sample-ecs-datamorph
      RetentionInDays: 7  # Optional

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      VpcId: vpc-f619ad8f # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8501 # Replace with an unique port value, but same as containerport
          ToPort: 8501 # Replace with an unique port value, but same as containerport
          CidrIp: 0.0.0.0/0

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-2320c15a  # Replace with your subnet
          SecurityGroups:
            - !Ref ServiceSecurityGroup
