name: Deploy from docker hub to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: datamorphproject/datamorph:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
    
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ecs/ecs_fargate.yml \
            --stack-name sample-ecs-datamorph-deployment-stack \
            --parameter-overrides DockerImage=$DOCKER_IMAGE \
            --capabilities CAPABILITY_NAMED_IAM